// ============================================================================
// GENERATE REPORT - Creates detailed REPORT file after task execution
// ============================================================================

import fs from 'fs/promises';
import path from 'path';

/**
 * Generate REPORT file
 *
 * @param {string} taskId - Task ID (e.g., TASK-0008)
 * @param {string} response - Claude API response
 * @param {object} changes - File changes {created, updated, deleted}
 * @param {object} checks - Check results {typecheck, lint, build, success}
 * @param {string} projectRoot - Project root directory
 */
export default async function generateReport(taskId, response, changes, checks, projectRoot) {
  const timestamp = new Date().toISOString();
  const reportFile = path.join(projectRoot, 'factory/results', `${taskId}-REPORT.md`);

  // Extract summary from Claude response
  const summary = extractSummary(response);

  const content = `# REPORT: ${taskId}

**Status**: ${checks.success ? 'SUCCESS ✅' : 'FAILED ❌'}
**Date**: ${timestamp}
**Agent**: ENGINEER (Claude Sonnet 4.5)

## Summary

${summary}

## File Changes

### Created (${changes.created.length})
${changes.created.length > 0 ? changes.created.map(f => `- \`${f}\``).join('\n') : '_No files created_'}

### Updated (${changes.updated.length})
${changes.updated.length > 0 ? changes.updated.map(f => `- \`${f}\``).join('\n') : '_No files updated_'}

### Deleted (${changes.deleted.length})
${changes.deleted.length > 0 ? changes.deleted.map(f => `- \`${f}\``).join('\n') : '_No files deleted_'}

## Verification Results

### TypeScript Check
**Status**: ${checks.typecheck.passed ? 'PASS ✅' : 'FAIL ❌'}

${checks.typecheck.passed ? '' : `
\`\`\`
${checks.typecheck.output}
\`\`\`
`}

### Lint Check
**Status**: ${checks.lint.passed ? 'PASS ✅' : 'FAIL ❌'}

${checks.lint.passed ? '' : `
\`\`\`
${checks.lint.output}
\`\`\`
`}

### Build Check
**Status**: ${checks.build.passed ? 'PASS ✅' : 'FAIL ❌'}

${checks.build.passed ? '' : `
\`\`\`
${checks.build.output}
\`\`\`
`}

## Claude Response

<details>
<summary>Full Claude Response (click to expand)</summary>

\`\`\`
${response}
\`\`\`

</details>

## Next Steps

${checks.success ? `
- [x] All checks passed
- [ ] Review code changes
- [ ] Merge PR to main
- [ ] Deploy to production
` : `
- [ ] Fix failing checks
- [ ] Review error messages above
- [ ] Re-run ENGINEER or fix manually
`}

---

**Generated by ENGINEER Runner** | [Task File](../tasks/${taskId}.md) | [Audit](../audit/)
`;

  // Ensure results directory exists
  await fs.mkdir(path.dirname(reportFile), { recursive: true });

  // Write REPORT
  await fs.writeFile(reportFile, content, 'utf-8');

  console.log(`  ✓ REPORT created: ${path.basename(reportFile)}`);
}

/**
 * Extract summary from Claude response
 */
function extractSummary(response) {
  // Try to extract SUMMARY section
  const summaryMatch = response.match(/## SUMMARY\n\n([\s\S]+?)(?=\n##|$)/);
  if (summaryMatch) {
    return summaryMatch[1].trim();
  }

  // Try to extract IMPLEMENTATION PLAN section
  const planMatch = response.match(/## IMPLEMENTATION PLAN\n\n([\s\S]+?)(?=\n##|$)/);
  if (planMatch) {
    return planMatch[1].trim();
  }

  // Fallback: return first paragraph
  const lines = response.split('\n');
  const firstParagraph = [];
  for (const line of lines) {
    if (line.trim() === '') break;
    if (line.startsWith('#')) continue;
    firstParagraph.push(line);
  }

  return firstParagraph.join('\n') || 'No summary available';
}
